### ISSUE TITLE
As a player in an ongoing game session, I suddenly decide to leave the session due to some reason.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#10]
### Acceptance Criteria
- [x] The player must have completed the current round, meaning he sees the results of the played round. That means the player must have placed the bet and wait until the results of the bet are visible. Only then can he exit the session. 
- [x] His statistics ( wins, losses etc.) are updated. 
- [x] The player ends up in the Dashboard. 

### Development Tasks
- [x] sopra-fs23-group-33/sopra-client#16
- [x] sopra-fs23-group-33/sopra-server#66
- [x] sopra-fs23-group-33/sopra-server#67

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
- Add a "Leave Room" button to the game interface. Medium, 2h.
- When the "Leave Room" button is clicked, verify that the player has completed the current round. Medium, 1h. 
- If the player has not completed the current round, display an error message indicating that they must wait until the results of their bet are visible before leaving the room. Medium, 2h.
- If the player has completed the current round, update their statistics (account balance, win-rate, etc.). Medium, 4h.
- Remove the player from the current game room and redirect it to the dashboard. Medium, 2h.
