### ISSUE TITLE
As a player, I want to receive power-ups in order for the game to be more competitive.  

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#11]
### Acceptance Criteria:

- [x] At the beginning of the game, a player receives a random combination of power-ups.
- [x] Some power-ups are:
    - Bail-Out: in case the player bets in the wrong direction, the entire position gets refunded. 
    - x2: your profit/loss is multiplied by factor two. 
    - x5: your profit/loss is multiplied by factor five. 
    - x10: your profit/loss is multiplied by factor ten. 
    - Hacker: get 10% of some players holdings
    - Cybersecurity: block a player (Hacker) that tries to steal 10% of your funds. 
- [x] The player can decide whether to activate the available power-ups. Power-ups can also be redeemed in later rounds. 

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-server#89
- [x] sopra-fs23-group-33/sopra-server#90
- [x] sopra-fs23-group-33/sopra-client#58
- [x] sopra-fs23-group-33/sopra-client#59
- [x] sopra-fs23-group-33/sopra-server#93
- [x] sopra-fs23-group-33/sopra-client#70
- [x] #117

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
- Create a database table to store the power-up information for each player. High, 8h.
- Add power-up logic to the game. High, 8h.
- Add a UI element to display which power-ups avaliable. High, 1h. 
- Add a UI element to allow the player to activate available power-ups. High, 2h,
- Update the player's statistics (account balance, win-rate, etc.) based on the power-up effects. Medium, 2h.
