### ISSUE TITLE
As a player in a game, I want events to occur during a round in order to make the game more competitive.  

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#12]
### Acceptance Criteria:
- [x] Events: 
    - [x] Robin Hood: the player with the most coins must distribute 5% of his holdings to the other players. 
    - [x] Money-Printer: the player receives 200 coins. 
    - [x] Capital Gains Tax: 25% is deducted from your profit of a winning bet. 
    - [x] Market Volatility: for the next round, all profit/losses are multiplied by factor two. 
- [x] The consequences of each event come immediately into effect. 

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-client#66
- [x] sopra-fs23-group-33/sopra-server#104
- [x] sopra-fs23-group-33/sopra-server#105
- [x] sopra-fs23-group-33/sopra-server#106
- [x] sopra-fs23-group-33/sopra-client#89

**Comment by COrtsJosep** [comment]
# Mein Vorschlag (verbesserungsfähig)
- Design a user interface pop-up that informs the users at the begining of the round that an event has taken place (if any). High, 8h.
- Design and implement the occurrence of the random events. High, 12h.
- Update the user's statistics after the event has taken place. High, 4h.
