### ISSUE TITLE
As a player in a game, I can see the result of the taken bet as soon as the time is up.  

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#13]
### Acceptance Criteria:
- [x] The player sees the result and statistics of his bet. These include: Betting amount, Bet direction, Profit/Loss, Updated total coins, Events if any
- [x] In addition, the player sees total balance & bet of the other players.
- [x] The "solution" chart
- [x] After a certain amount of time, the next round begins automatically. 

### Development Tasks:

- [x] sopra-fs23-group-33/sopra-server#68
- [x] sopra-fs23-group-33/sopra-client#17
- [x] sopra-fs23-group-33/sopra-server#70
- [x] sopra-fs23-group-33/sopra-client#18
- [x] sopra-fs23-group-33/sopra-server#72
- [x] sopra-fs23-group-33/sopra-client#54
- [x] sopra-fs23-group-33/sopra-client#57
- [x] sopra-fs23-group-33/sopra-client#71

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
- Create a function to calculate the profit/loss of the bet based on the entered coins, and bet direction. High, 2h.
- Design the user interface for displaying the chart and the bet result. High, 4h.
- Develop a database schema to store the bet history, including the bet direction, coins used, profit/loss, and power-ups used. High, 12h.
- Design and implement the user interface for displaying the impact of power-ups and events on the bet result. Low, 2h.
- Integrate feature that starts the next round automatically after a certain amount of time. High, 2h.

**Comment by stsaxe** [comment]
it is not posible to display the effect of powerups because they are stackable. An X2 pwoerup in combination with an x10 powerup results in X20. The individual effects of X2 and X10 are no longer determinable.
