### ISSUE TITLE
As an already registered user, I want to log in to my account.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#2]
### Acceptance Criteria
- [x] The username & password have to match an existing user. If not, an error is displayed.
- [x] An unregistered user can access the registration page from the login page.
- [x] Upon successful login, the user is redirected to the dashboard.

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-client#3
- [x] sopra-fs23-group-33/sopra-server#28
- [x] sopra-fs23-group-33/sopra-client#4
- [x] sopra-fs23-group-33/sopra-server#30
- [x] sopra-fs23-group-33/sopra-client#82
- [x] sopra-fs23-group-33/sopra-server#32
- [x] sopra-fs23-group-33/sopra-client#73

**Comment by COrtsJosep** [comment]
## Mein Vorschlag
### Für diese US:
- Design a user login form for registered users. High, 4h.
- Create a server-side script to manage the login request. High, 3h.
- Implement client-side managing and display of the output of the login request. Medium, 4h.
- Implement redirection to dashboard upon successful login. High, 1h.
-  Implement automatic login for registered users by creating a session token. Low, 4h.

### Und dann würde ich eine neue US, etwa so wie "As a logged/registered user I want to access my profile/dashboard where I have access to account information and statistics", mit solche Tasks:
- Create a dashboard page that shows the user's account details upon successful registration or login. High, 8h.
- The dashboard also contains the following data: account balance, number of won and lost trades, total rounds played etc. High, 4h.
- Create a logout button, or automatic logout if the browser is closed. Medium, 4h.
