### ISSUE TITLE
As a logged in user, I want to access my profile/dashboard where I have access to account information and statistics.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#20]
### Acceptance Criteria:
- [x] The user’s Dashboard is only accessible for logged-in users. 
- [x] The Dashboard contains the following data: number of won and lost trades, total rounds played etc. 

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-client#5
- [x] sopra-fs23-group-33/sopra-client#6
- [x] sopra-fs23-group-33/sopra-client#7
- [x] sopra-fs23-group-33/sopra-server#36
