### ISSUE TITLE
As a logged in user, I want to see which other users are online in order to be able to play with each other. This can be found in the Dashboard.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#3]
### Acceptance Criteria:
- [x] A user can view a list of all registered users (user overview). 
- [x] The table contains Username, Total Rounds Played, Win Rate & Status. 
- [x] The users overview and the profile page are only accessible for logged-in users. 
- [x] The table is updated in real-time.

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-client#8
- [x] sopra-fs23-group-33/sopra-client#100
- [x] sopra-fs23-group-33/sopra-client#9
- [x] sopra-fs23-group-33/sopra-client#32

**Comment by COrtsJosep** [comment]
## Mein Vorschlag
- Implement a user overview section in the dashboard that shows a list of all registered users and their online status. High, 4h.
- Implement server-side code to retrieve user statistics information from the database and display it on the user's profile page. High, 1h.
- Implement client-side code to allow users to hover over a username in the user overview page to display their statistics. Low, 4h.
- Implement page guards to prevent access from non-logged users. Medium, 2h.
