### ISSUE TITLE
As a user, I want to create a new game lobby or join an existing one from a list of available lobbies, in order to play the game.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#4]
### Acceptance Criteria:
- [x] A user can see the available game lobbies. 
- [x] The available lobbies updated in real-time. 
- [x] A user can create a new lobby, which can be named and the maximum number of players in a lobby can be defined. 
- [x] Users can join a lobby through the Dashboard. 
- [x] Upon joining a lobby, a user is in the game lobby.

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-client#10
- [x] sopra-fs23-group-33/sopra-server#42
- [x] sopra-fs23-group-33/sopra-server#43
- [x] sopra-fs23-group-33/sopra-server#44
- [x] sopra-fs23-group-33/sopra-client#11
- [x] sopra-fs23-group-33/sopra-client#12
- [x] sopra-fs23-group-33/sopra-client#33
- [x] sopra-fs23-group-33/sopra-client#34
- [x] sopra-fs23-group-33/sopra-server#49
- [x] sopra-fs23-group-33/sopra-server#88
- [x] sopra-fs23-group-33/sopra-client#79
- [x] sopra-fs23-group-33/sopra-client#103
- [x] sopra-fs23-group-33/sopra-client#90

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
## Ich würde gerne mit #5 zusammenfügen.
- Implement client-side window (from the dashboard) to create a new room, with parameters: name, maximum number of players. High, 4h.
- Create a database schema to store information about available game rooms, including the room name, number of players, and the players' usernames. High, 8h.
- Implement server-side input validation for room creation as well as room joining requests. Low, 2h.
- Implement request system to create, modify, get information about rooms. High, 6h. 
- Implement client-side code to display the list of available game rooms and their information in real-time. High, 6h.
- Implement client-side code to join an existing room. High, 2h.
- Implement page guards to prevent joining of non-logged users. Low, 2h.
- Implement redirection to lobby after successful room creation or joining. High, 2h.
