### ISSUE TITLE
As a player in a game session, I want to see the chart, my available coins and power-ups in order to place a LONG or SHORT bet.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#8]
### Acceptance Criteria:
- [x] Chart data is pulled in real time via the API 
- [x] Chart is updated in real-time. 

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-server#54
- [x] sopra-fs23-group-33/sopra-client#14
- [x] sopra-fs23-group-33/sopra-client#47
- [x] sopra-fs23-group-33/sopra-client#44
- [x] sopra-fs23-group-33/sopra-client#45
- [x] sopra-fs23-group-33/sopra-client#46
- [x] sopra-fs23-group-33/sopra-server#56
- [x] sopra-fs23-group-33/sopra-client#35
- [x] sopra-fs23-group-33/sopra-client#67
- [x] sopra-fs23-group-33/sopra-client#91

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
- Integrate with a third-party charting API to retrieve real-time chart data. High, 8h.
- Design and implement the user interface for displaying the chart and available coins/power-ups in the game room. High, 4h.
- Integrate with a third-party charting API to retrieve real-time chart data. High, 4h.
- Implement server-side code to retrieve and update the user's available coins and power-ups in real-time. High, 8h.
- Implement page guards to prevent nonlogged user access. Low, 1h.
