### ISSUE TITLE
As a player in a game session, I want to type in the number of coins I would like to use in for the bet in order to long or short the market. Additionally, I want to enable power-ups which can benefit me.

### ISSUE THREAD

**Issue by Marlet12** [sopra-fs23-group-33/sopra-server#9]
### Acceptance Criteria:
- [x] There is a text field to enter the number coins to use for the bet. 
- [x] A “Short” button to bet on falling prices and a “Long” button to bet on rising prices. 
- [x] All players have a limited amount of time to look at the chart and place their bets.
- [x] A player can see the available amount of coins.

### Development Tasks:
- [x] sopra-fs23-group-33/sopra-server#58
- [x] sopra-fs23-group-33/sopra-client#15
- [x] sopra-fs23-group-33/sopra-server#60
- [x] sopra-fs23-group-33/sopra-client#22
- [x] sopra-fs23-group-33/sopra-server#62
- [x] sopra-fs23-group-33/sopra-client#51
- [x] sopra-fs23-group-33/sopra-client#52
- [x] sopra-fs23-group-33/sopra-client#55
- [x] sopra-fs23-group-33/sopra-client#56
- [x] sopra-fs23-group-33/sopra-client#76

**Comment by COrtsJosep** [comment]
# Mein Vorschlag
 -Implement server-side code to handle the user's decisions and update the game state accordingly. High, 6h.
- Implement client-side code to update game display according to the game state. High, 2h.
- Implement server-side code to handle the user's bet and update the game state accordingly. High, 4h.
- Implement server-side code to handle the game timer and notify users when the time to place bets has expired. Medium, 6h.
- Implement error handling mechanisms to ensure that the user cannot make invalid moves, and provide appropriate error messages. Medium, 4h. (Server- oder client-side?)
